sudo: false
language: java
script:
- 'mvn -s .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
jdk:
- oraclejdk8
notifications:
  slack:
    secure: oYUUnTQPUtxgxjELWlQyBTS0yV+MQbCTKI4+rDw8cIeO04EpYKkMAidTNs9ysC2j+VDMe7bRvm82zQwCPKWZQJ21nbzFG3f+Noavf1Akh0Vx6qhQU/vHhDsAy2hiPaUHFSS3KQAXbi7ArnOKhB+yYoJExLB4tbGNkUeu3DdxueAlDs42b6U6Zs3Ez8vZyyjM66Lr52Yp/mlQA6GtBzMwK3UClrozALPSDMEnvcc9MGi7Zd4ULD7PJpjHb7XHYNP/3+A1vbeIcM3WWfRnBCl6ku772ODG/b9Q4sq/PJya/LxpD88orp2Xq+vfoxF9hrZqoeEzYAE5PUP8LfUfbfbDkgkWQ3VOnD0Ox4I35ICKcQAQ6Y+TcrHzSG52doSVbaayGT+jwKY7INV0Ar3tmfFDSaSxYoMuv95i/E0xQUhUNWdz71Cp2w5zyRei9l+oHg+DpKv12Slis+RCfE/JHWNdn6elrwuhcWtrkYOv0JU5PPovvd24ZaBjaD7iEktBr3d8hHGdiNzLwAjgr5fBAIp0SmFqQ5Jplmeisj0BgPI/H6IIbCJYQyFzQLAlOkFliNfVeTzr4bytziaqzoxJvOtgxgDwidy1fdMI68q9Ny3CTNCuOUtpDRBWYlqhbtKnfdNA7/U/we7CG5H4axMkR0KyMYXPQ/RusfNkhbFa0UAIWeo=
